<?php declare(strict_types=1);
/*
 * FACT-Finder REST API Client
 * Copyright © webweit GmbH (https://www.webweit.de)
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

namespace Web\FactFinderApi\Client\V1\Api;

use GuzzleHttp6\Psr7\Request;
use Web\FactFinderApi\Client\ObjectSerializer;

class CampaignApi extends ApiClient
{
    /**
     * Operation getPageCampaignsUsingGET
     *
     * Get page campaigns
     *
     * @param string $channel        channel (required)
     * @param string $page_id        Use this parameter to pass a page ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     *
     * @return \Web\FactFinderApi\Client\V1\Model\Campaign[]
     */
    public function getPageCampaignsUsingGET(string $channel, $page_id, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        list($response) = $this->getPageCampaignsUsingGETWithHttpInfo($channel, $page_id, $ids_only, $sid, $advisor_status);

        return $response;
    }

    /**
     * Operation getPageCampaignsUsingGETWithHttpInfo
     *
     * Get page campaigns
     *
     * @param string $channel        channel (required)
     * @param string $page_id        Use this parameter to pass a page ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     *
     * @return array of \Web\FactFinderApi\Client\V1\Model\Campaign[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getPageCampaignsUsingGETWithHttpInfo(string $channel, $page_id, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        $request = $this->getPageCampaignsUsingGETRequest($channel, $page_id, $ids_only, $sid, $advisor_status);

        return $this->executeRequest($request, '\Web\FactFinderApi\Client\V1\Model\Campaign[]');
    }

    /**
     * Operation getProductCampaignsUsingGET
     *
     * Get product campaigns
     *
     * @param string $channel        channel (required)
     * @param string $product_number Use this parameter to pass a product ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     *
     * @return \Web\FactFinderApi\Client\V1\Model\Campaign[]
     */
    public function getProductCampaignsUsingGET(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        list($response) = $this->getProductCampaignsUsingGETWithHttpInfo($channel, $product_number, $ids_only, $sid, $advisor_status);

        return $response;
    }

    /**
     * Operation getProductCampaignsUsingGETWithHttpInfo
     *
     * Get product campaigns
     *
     * @param string $channel        channel (required)
     * @param string $product_number Use this parameter to pass a product ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     *
     * @return array of \Web\FactFinderApi\Client\V1\Model\Campaign[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getProductCampaignsUsingGETWithHttpInfo(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        $request = $this->getProductCampaignsUsingGETRequest($channel, $product_number, $ids_only, $sid, $advisor_status);

        return $this->executeRequest($request, '\Web\FactFinderApi\Client\V1\Model\Campaign[]');
    }

    /**
     * Operation getProductCampaignsUsingGETAsync
     *
     * Get product campaigns
     *
     * @param string $channel        channel (required)
     * @param string $product_number Use this parameter to pass a product ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function getProductCampaignsUsingGETAsync(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        return $this->getProductCampaignsUsingGETAsyncWithHttpInfo($channel, $product_number, $ids_only, $sid, $advisor_status)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getProductCampaignsUsingGETAsyncWithHttpInfo
     *
     * Get product campaigns
     *
     * @param string $channel        channel (required)
     * @param string $product_number Use this parameter to pass a product ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function getProductCampaignsUsingGETAsyncWithHttpInfo(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        $request = $this->getProductCampaignsUsingGETRequest($channel, $product_number, $ids_only, $sid, $advisor_status);

        return $this->executeAsyncRequest($request, '\Web\FactFinderApi\Client\V1\Model\Campaign[]');
    }

    /**
     * Operation getShoppingCartCampaignsUsingGET
     *
     * Get shopping cart campaigns
     *
     * @param string   $channel        channel (required)
     * @param string[] $product_number Use this parameter to pass product ID(s) for which you wish to obtain campaigns. (required)
     * @param bool     $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string   $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string   $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     *
     * @return \Web\FactFinderApi\Client\V1\Model\Campaign[]
     */
    public function getShoppingCartCampaignsUsingGET(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        list($response) = $this->getShoppingCartCampaignsUsingGETWithHttpInfo($channel, $product_number, $ids_only, $sid, $advisor_status);

        return $response;
    }

    /**
     * Operation getShoppingCartCampaignsUsingGETWithHttpInfo
     *
     * Get shopping cart campaigns
     *
     * @param string   $channel        channel (required)
     * @param string[] $product_number Use this parameter to pass product ID(s) for which you wish to obtain campaigns. (required)
     * @param bool     $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string   $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string   $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     *
     * @return array of \Web\FactFinderApi\Client\V1\Model\Campaign[], HTTP status code, HTTP response headers (array of strings)
     */
    public function getShoppingCartCampaignsUsingGETWithHttpInfo(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        $request = $this->getShoppingCartCampaignsUsingGETRequest($channel, $product_number, $ids_only, $sid, $advisor_status);

        return $this->executeRequest($request, '\Web\FactFinderApi\Client\V1\Model\Campaign[]');
    }

    /**
     * Operation getShoppingCartCampaignsUsingGETAsync
     *
     * Get shopping cart campaigns
     *
     * @param string   $channel        channel (required)
     * @param string[] $product_number Use this parameter to pass product ID(s) for which you wish to obtain campaigns. (required)
     * @param bool     $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string   $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string   $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function getShoppingCartCampaignsUsingGETAsync(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        return $this->getShoppingCartCampaignsUsingGETAsyncWithHttpInfo($channel, $product_number, $ids_only, $sid, $advisor_status)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getShoppingCartCampaignsUsingGETAsyncWithHttpInfo
     *
     * Get shopping cart campaigns
     *
     * @param string   $channel        channel (required)
     * @param string[] $product_number Use this parameter to pass product ID(s) for which you wish to obtain campaigns. (required)
     * @param bool     $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string   $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string   $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function getShoppingCartCampaignsUsingGETAsyncWithHttpInfo(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        $request = $this->getShoppingCartCampaignsUsingGETRequest($channel, $product_number, $ids_only, $sid, $advisor_status);

        return $this->executeAsyncRequest($request, '\Web\FactFinderApi\Client\V1\Model\Campaign[]');
    }

    /**
     * Create request for operation 'getPageCampaignsUsingGET'
     *
     * @param string $channel        channel (required)
     * @param string $page_id        Use this parameter to pass a page ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return Request
     */
    protected function getPageCampaignsUsingGETRequest(string $channel, string $page_id, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        $resourcePath = '/v1/campaign/{channel}/page';
        $queryParams = [];
        $httpBody = '';

        // query params
        if ($ids_only !== null) {
            $queryParams['idsOnly'] = ObjectSerializer::toQueryValue($ids_only);
        }
        // query params
        if ($page_id !== null) {
            $queryParams['pageId'] = ObjectSerializer::toQueryValue($page_id);
        }
        // query params
        if ($sid !== null) {
            $queryParams['sid'] = ObjectSerializer::toQueryValue($sid);
        }
        // query params
        if ($advisor_status !== null) {
            $queryParams['advisorStatus'] = ObjectSerializer::toQueryValue($advisor_status);
        }

        // path params
        $resourcePath = $this->addChannelToResourcePath($channel, $resourcePath);

        return $this->getQuery($resourcePath, $queryParams);
    }

    /**
     * Create request for operation 'getProductCampaignsUsingGET'
     *
     * @param string $channel        channel (required)
     * @param string $product_number Use this parameter to pass a product ID for which you wish to obtain campaigns. (required)
     * @param bool   $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function getProductCampaignsUsingGETRequest(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling getProductCampaignsUsingGET'
            );
        }
        // verify the required parameter 'product_number' is set
        if ($product_number === null || (\is_array($product_number) && \count($product_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_number when calling getProductCampaignsUsingGET'
            );
        }

        $resourcePath = '/v1/campaign/{channel}/product';
        $queryParams = [];
        $httpBody = '';
        // query params
        if ($ids_only !== null) {
            $queryParams['idsOnly'] = ObjectSerializer::toQueryValue($ids_only);
        }
        // query params
        if ($product_number !== null) {
            $queryParams['productNumber'] = ObjectSerializer::toQueryValue($product_number);
        }
        // query params
        if ($sid !== null) {
            $queryParams['sid'] = ObjectSerializer::toQueryValue($sid);
        }
        // query params
        if ($advisor_status !== null) {
            $queryParams['advisorStatus'] = ObjectSerializer::toQueryValue($advisor_status);
        }

        // path params
        $resourcePath = $this->addChannelToResourcePath($channel, $resourcePath);

        return $this->getQuery($resourcePath, $queryParams);
    }

    /**
     * Create request for operation 'getShoppingCartCampaignsUsingGET'
     *
     * @param string   $channel        channel (required)
     * @param string[] $product_number Use this parameter to pass product ID(s) for which you wish to obtain campaigns. (required)
     * @param bool     $ids_only       If the value true is passed, then only the record IDs will be returned, streamlining the results. If you do not need the other information in the results, this will help you to improve performance. (optional, default to false)
     * @param string   $sid            This parameter is used to pass an id for the user session. This is important for recognising the user, if you want to trigger personalised campaigns, as well as for FACT-Finder tracking. (optional)
     * @param string   $advisor_status For specifying the current campaign id and answer path; format: campaignId-answerPath (optional)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function getShoppingCartCampaignsUsingGETRequest(string $channel, $product_number, bool $ids_only = false, $sid = null, $advisor_status = null)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling getShoppingCartCampaignsUsingGET'
            );
        }
        // verify the required parameter 'product_number' is set
        if ($product_number === null || (\is_array($product_number) && \count($product_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $product_number when calling getShoppingCartCampaignsUsingGET'
            );
        }

        $resourcePath = '/v1/campaign/{channel}/shoppingcart';
        $queryParams = [];
        $httpBody = '';
        // query params
        if ($ids_only !== null) {
            $queryParams['idsOnly'] = ObjectSerializer::toQueryValue($ids_only);
        }
        // query params
        if (\is_array($product_number)) {
            $queryParams['productNumber'] = $product_number;
        } elseif ($product_number !== null) {
            $queryParams['productNumber'] = ObjectSerializer::toQueryValue($product_number);
        }
        // query params
        if ($sid !== null) {
            $queryParams['sid'] = ObjectSerializer::toQueryValue($sid);
        }
        // query params
        if ($advisor_status !== null) {
            $queryParams['advisorStatus'] = ObjectSerializer::toQueryValue($advisor_status);
        }

        // path params
        $resourcePath = $this->addChannelToResourcePath($channel, $resourcePath);

        return $this->getQuery($resourcePath, $queryParams);
    }
}
