<?php declare(strict_types=1);
/*
 * FACT-Finder REST API Client
 * Copyright © webweit GmbH (https://www.webweit.de)
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

namespace Web\FactFinderApi\Client\V1\Api;

use GuzzleHttp6\Client;
use GuzzleHttp6\ClientInterface;
use GuzzleHttp6\Exception\RequestException;
use GuzzleHttp6\Psr7\Request;
use GuzzleHttp6\RequestOptions;
use Web\FactFinderApi\Client\ApiClient;
use Web\FactFinderApi\Client\ApiException;
use Web\FactFinderApi\Client\Configuration;
use Web\FactFinderApi\Client\HeaderSelector;
use Web\FactFinderApi\Client\ObjectSerializer;

/**
 * TrackingApi Class Doc Comment
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class TrackingApi extends ApiClient
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation trackCartUsingPOST
     *
     * Track a cart event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackCartUsingPOST($channel, $events): void
    {
        $this->trackCartUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackCartUsingPOSTWithHttpInfo
     *
     * Track a cart event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackCartUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackCartUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackCartUsingPOSTAsync
     *
     * Track a cart event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackCartUsingPOSTAsync($channel, $events)
    {
        return $this->trackCartUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackCartUsingPOSTAsyncWithHttpInfo
     *
     * Track a cart event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackCartUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackCartUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Operation trackCheckoutUsingPOST
     *
     * Track a checkout event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackCheckoutUsingPOST($channel, $events): void
    {
        $this->trackCheckoutUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackCheckoutUsingPOSTWithHttpInfo
     *
     * Track a checkout event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackCheckoutUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackCheckoutUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackCheckoutUsingPOSTAsync
     *
     * Track a checkout event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackCheckoutUsingPOSTAsync($channel, $events)
    {
        return $this->trackCheckoutUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackCheckoutUsingPOSTAsyncWithHttpInfo
     *
     * Track a checkout event
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackCheckoutUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackCheckoutUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Operation trackClickUsingPOST
     *
     * Track a click event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\ClickEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackClickUsingPOST($channel, $events): void
    {
        $this->trackClickUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackClickUsingPOSTWithHttpInfo
     *
     * Track a click event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\ClickEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackClickUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackClickUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackClickUsingPOSTAsync
     *
     * Track a click event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\ClickEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackClickUsingPOSTAsync($channel, $events)
    {
        return $this->trackClickUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackClickUsingPOSTAsyncWithHttpInfo
     *
     * Track a click event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\ClickEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackClickUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackClickUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Operation trackFeedbackUsingPOST
     *
     * Track a feedback event
     *
     * @param string                                             $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\FeedbackEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackFeedbackUsingPOST($channel, $events): void
    {
        $this->trackFeedbackUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackFeedbackUsingPOSTWithHttpInfo
     *
     * Track a feedback event
     *
     * @param string                                             $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\FeedbackEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackFeedbackUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackFeedbackUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackFeedbackUsingPOSTAsync
     *
     * Track a feedback event
     *
     * @param string                                             $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\FeedbackEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackFeedbackUsingPOSTAsync($channel, $events)
    {
        return $this->trackFeedbackUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackFeedbackUsingPOSTAsyncWithHttpInfo
     *
     * Track a feedback event
     *
     * @param string                                             $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\FeedbackEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackFeedbackUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackFeedbackUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Operation trackLogUsingPOST
     *
     * Track a log event
     *
     * @param string                                              $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\SearchLogEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackLogUsingPOST($channel, $events): void
    {
        $this->trackLogUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackLogUsingPOSTWithHttpInfo
     *
     * Track a log event
     *
     * @param string                                              $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\SearchLogEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackLogUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackLogUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackLogUsingPOSTAsync
     *
     * Track a log event
     *
     * @param string                                              $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\SearchLogEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackLogUsingPOSTAsync($channel, $events)
    {
        return $this->trackLogUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackLogUsingPOSTAsyncWithHttpInfo
     *
     * Track a log event
     *
     * @param string                                              $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\SearchLogEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackLogUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackLogUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Operation trackLoginUsingPOST
     *
     * Track a login event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\LoginEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackLoginUsingPOST($channel, $events): void
    {
        $this->trackLoginUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackLoginUsingPOSTWithHttpInfo
     *
     * Track a login event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\LoginEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackLoginUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackLoginUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackLoginUsingPOSTAsync
     *
     * Track a login event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\LoginEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackLoginUsingPOSTAsync($channel, $events)
    {
        return $this->trackLoginUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackLoginUsingPOSTAsyncWithHttpInfo
     *
     * Track a login event
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\LoginEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackLoginUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackLoginUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Operation trackRecommendationClickUsingPOST
     *
     * Track a recommendation click event
     *
     * @param string                                                        $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\RecommendationClickEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     */
    public function trackRecommendationClickUsingPOST($channel, $events): void
    {
        $this->trackRecommendationClickUsingPOSTWithHttpInfo($channel, $events);
    }

    /**
     * Operation trackRecommendationClickUsingPOSTWithHttpInfo
     *
     * Track a recommendation click event
     *
     * @param string                                                        $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\RecommendationClickEvent[] $events  events (required)
     *
     * @throws \Web\FactFinderApi\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     *
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function trackRecommendationClickUsingPOSTWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackRecommendationClickUsingPOSTRequest($channel, $events);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    \sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 401:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 403:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
                case 500:
                    $e->setResponseObject($this->prepareErrorObject($e));
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation trackRecommendationClickUsingPOSTAsync
     *
     * Track a recommendation click event
     *
     * @param string                                                        $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\RecommendationClickEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackRecommendationClickUsingPOSTAsync($channel, $events)
    {
        return $this->trackRecommendationClickUsingPOSTAsyncWithHttpInfo($channel, $events)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation trackRecommendationClickUsingPOSTAsyncWithHttpInfo
     *
     * Track a recommendation click event
     *
     * @param string                                                        $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\RecommendationClickEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Promise\PromiseInterface
     */
    public function trackRecommendationClickUsingPOSTAsyncWithHttpInfo($channel, $events)
    {
        $returnType = '';
        $request = $this->trackRecommendationClickUsingPOSTRequest($channel, $events);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception): void {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        \sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'trackCartUsingPOST'
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackCartUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackCartUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackCartUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/cart';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'trackCheckoutUsingPOST'
     *
     * @param string                                                   $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\CartOrCheckoutEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackCheckoutUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackCheckoutUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackCheckoutUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/checkout';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'trackClickUsingPOST'
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\ClickEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackClickUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackClickUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackClickUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/click';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'trackFeedbackUsingPOST'
     *
     * @param string                                             $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\FeedbackEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackFeedbackUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackFeedbackUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackFeedbackUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/feedback';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'trackLogUsingPOST'
     *
     * @param string                                              $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\SearchLogEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackLogUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackLogUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackLogUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/log';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'trackLoginUsingPOST'
     *
     * @param string                                          $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\LoginEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackLoginUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackLoginUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackLoginUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/login';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create request for operation 'trackRecommendationClickUsingPOST'
     *
     * @param string                                                        $channel channel (required)
     * @param \Web\FactFinderApi\Client\V1\Model\RecommendationClickEvent[] $events  events (required)
     *
     * @throws \InvalidArgumentException
     *
     * @return \GuzzleHttp6\Psr7\Request
     */
    protected function trackRecommendationClickUsingPOSTRequest($channel, $events)
    {
        // verify the required parameter 'channel' is set
        if ($channel === null || (\is_array($channel) && \count($channel) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $channel when calling trackRecommendationClickUsingPOST'
            );
        }
        // verify the required parameter 'events' is set
        if ($events === null || (\is_array($events) && \count($events) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $events when calling trackRecommendationClickUsingPOST'
            );
        }

        $resourcePath = '/v1/track/{channel}/recommendationClick';
        $queryParams = [];
        $httpBody = '';
        // path params
        if ($channel !== null) {
            $resourcePath = \str_replace(
                '{channel}',
                ObjectSerializer::toPathValue($channel),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($events)) {
            $_tempBody = $events;
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/xml', 'application/json'],
            ['application/xml', 'application/json']
        );

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;

            if ($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp6\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if (\is_array($httpBody)) {
                    $httpBody = \GuzzleHttp6\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = \array_merge(
            $defaultHeaders,
            $headers
        );

        $query = \GuzzleHttp6\Psr7\build_query($queryParams);

        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     *
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = \fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
