<?php declare(strict_types=1);
/*
 * FACT-Finder REST API Client
 * Copyright © webweit GmbH (https://www.webweit.de)
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

namespace Web\FactFinderApi\Client\V1\Model;

use Web\FactFinderApi\Client\Model\BaseModel;

/**
 * SingleWordSearchResult Class Doc Comment
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class SingleWordSearchResult extends BaseModel
{
    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'SingleWordSearchResult';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'preview_records' => '\Web\FactFinderApi\Client\V1\Model\SearchRecord[]',
        'record_count' => 'int',
        'search_params' => '\Web\FactFinderApi\Client\V1\Model\Params',
        'word' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    protected static $swaggerFormats = [
        'preview_records' => null,
        'record_count' => 'int32',
        'search_params' => null,
        'word' => null,
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'preview_records' => 'previewRecords',
        'record_count' => 'recordCount',
        'search_params' => 'searchParams',
        'word' => 'word',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'preview_records' => 'setPreviewRecords',
        'record_count' => 'setRecordCount',
        'search_params' => 'setSearchParams',
        'word' => 'setWord',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'preview_records' => 'getPreviewRecords',
        'record_count' => 'getRecordCount',
        'search_params' => 'getSearchParams',
        'word' => 'getWord',
    ];

    /**
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['preview_records'] = $data['preview_records'] ?? null;
        $this->container['record_count'] = $data['record_count'] ?? null;
        $this->container['search_params'] = $data['search_params'] ?? null;
        $this->container['word'] = $data['word'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['preview_records'] === null) {
            $invalidProperties[] = "'preview_records' can't be null";
        }
        if ($this->container['record_count'] === null) {
            $invalidProperties[] = "'record_count' can't be null";
        }
        if ($this->container['word'] === null) {
            $invalidProperties[] = "'word' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * @return \Web\FactFinderApi\Client\V1\Model\SearchRecord[]
     */
    public function getPreviewRecords()
    {
        return $this->container['preview_records'];
    }

    /**
     * @param \Web\FactFinderApi\Client\V1\Model\SearchRecord[] $preview_records preview_records
     *
     * @return $this
     */
    public function setPreviewRecords($preview_records)
    {
        $this->container['preview_records'] = $preview_records;

        return $this;
    }

    /**
     * @return int
     */
    public function getRecordCount()
    {
        return $this->container['record_count'];
    }

    /**
     * @param int $record_count record_count
     *
     * @return $this
     */
    public function setRecordCount($record_count)
    {
        $this->container['record_count'] = $record_count;

        return $this;
    }

    /**
     * @return \Web\FactFinderApi\Client\V1\Model\Params
     */
    public function getSearchParams()
    {
        return $this->container['search_params'];
    }

    /**
     * @param \Web\FactFinderApi\Client\V1\Model\Params $search_params search_params
     *
     * @return $this
     */
    public function setSearchParams($search_params)
    {
        $this->container['search_params'] = $search_params;

        return $this;
    }

    /**
     * @return string
     */
    public function getWord()
    {
        return $this->container['word'];
    }

    /**
     * @param string $word word
     *
     * @return $this
     */
    public function setWord($word)
    {
        $this->container['word'] = $word;

        return $this;
    }
}
