<?php declare(strict_types=1);
/*
 * FACT-Finder REST API Client
 * Copyright © webweit GmbH (https://www.webweit.de)
 */

/**
 * FACT-Finder REST-API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V3
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

namespace Web\FactFinderApi\Client\V3\Model;

use Web\FactFinderApi\Client\Model\BaseModel;

/**
 * GeoInformation Class Doc Comment
 *
 * @author   Swagger Codegen team
 *
 * @see     https://github.com/swagger-api/swagger-codegen
 */
class GeoInformation extends BaseModel
{
    /**
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->container['distance'] = $data['distance'] ?? null;
        $this->container['location'] = $data['location'] ?? null;
        $this->container['master_values'] = $data['master_values'] ?? null;
        $this->container['variant_values'] = $data['variant_values'] ?? null;
    }

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    public static function swaggerTypes(): array
    {
        return [
            'distance' => 'double',
            'location' => '\Web\FactFinderApi\Client\V3\Model\Location',
            'master_values' => 'object',
            'variant_values' => '\Web\FactFinderApi\Client\V3\Model\VariantValues[]',
        ];
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     */
    public static function swaggerFormats(): array
    {
        return [
            'distance' => 'double',
            'location' => null,
            'master_values' => null,
            'variant_values' => null,
        ];
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    public static function attributeMap(): array
    {
        return [
            'distance' => 'distance',
            'location' => 'location',
            'master_values' => 'masterValues',
            'variant_values' => 'variantValues',
        ];
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    public static function setters(): array
    {
        return [
            'distance' => 'setDistance',
            'location' => 'setLocation',
            'master_values' => 'setMasterValues',
            'variant_values' => 'setVariantValues',
        ];
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    public static function getters(): array
    {
        return [
            'distance' => 'getDistance',
            'location' => 'getLocation',
            'master_values' => 'getMasterValues',
            'variant_values' => 'getVariantValues',
        ];
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['distance'] === null) {
            $invalidProperties[] = "'distance' can't be null";
        }
        if ($this->container['variant_values'] === null) {
            $invalidProperties[] = "'variant_values' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * @return float
     */
    public function getDistance()
    {
        return $this->container['distance'];
    }

    /**
     * @param float $distance The distance between market and search location in km. If the market is the online store, this is set to -1.
     *
     * @return $this
     */
    public function setDistance($distance)
    {
        $this->container['distance'] = $distance;

        return $this;
    }

    /**
     * @return \Web\FactFinderApi\Client\V3\Model\Location
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * @param \Web\FactFinderApi\Client\V3\Model\Location $location The market's location. Is missing if the market is the online store.
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * @return object
     */
    public function getMasterValues()
    {
        return $this->container['master_values'];
    }

    /**
     * @param object $master_values the field values, which are specific to this market
     *
     * @return $this
     */
    public function setMasterValues($master_values)
    {
        $this->container['master_values'] = $master_values;

        return $this;
    }

    /**
     * @return \Web\FactFinderApi\Client\V3\Model\VariantValues[]
     */
    public function getVariantValues()
    {
        return $this->container['variant_values'];
    }

    /**
     * @param \Web\FactFinderApi\Client\V3\Model\VariantValues[] $variant_values Contains variants. The values are mapped from field names to the field value.
     *
     * @return $this
     */
    public function setVariantValues($variant_values)
    {
        $this->container['variant_values'] = $variant_values;

        return $this;
    }
}
